# Site settings
title: "Third World Nomad"
header-img: "img/home-bg.jpg"
email: "kristiadi7@gmail.com"
description: "Thoughts, experiences, field reports, and tech blogs from third world, nomad-wannabe, software developer"
baseurl: ""
url: "http://wiseodd.github.io"
twitter_username: "wiseodd"
github_username: "wiseodd"
facebook_username: "agustinus.kristiadi7"

# Build settings
markdown: redcarpet
highlighter: "pygments"
permalink: "pretty"
paginate: 10
timezone: "Asia/Jakarta"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
gems: ["jekyll-paginate"]

redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
